import type { Location, Resource, ExtraOption } from '../types';

export const LOCATIONS: Location[] = [
    { id: 'unbox_uni', name: 'Unbox Uni', address: 'Тбел Абусеридзе, 38' },
    { id: 'unbox_one', name: 'Unbox One', address: 'Палиашвили, 4' },
    { id: 'neo_school', name: 'Neo School', address: 'Алесандра Сулаберидзе, 80' },
];

export const RESOURCES: Resource[] = [
    // Unbox One (Палиашвили 4, Батуми)
    {
        id: 'unbox_one_room_1',
        name: 'Кабинет 1',
        type: 'cabinet',
        hourlyRate: 20,
        capacity: 4,
        locationId: 'unbox_one',
        area: 9,
        minBookingHours: 1,
        formats: ['individual'],
        description: 'Уютный кабинет с песочной терапией для индивидуальной, детской и семейной работы. Тёплые тона, мягкое освещение, полная звукоизоляция.',
        photos: ['/img/offices/miniature_cab_1_pal.jpg'],
        services: ['sandbox', 'soundproof', 'climate_control', 'wifi'],
        sortOrder: 1,
    },
    {
        id: 'unbox_one_room_2',
        name: 'Кабинет 2',
        type: 'cabinet',
        hourlyRate: 20,
        capacity: 4,
        locationId: 'unbox_one',
        area: 12,
        minBookingHours: 1,
        formats: ['individual'],
        description: 'Кабинет в нейтральных тонах для индивидуальной терапии и семейных консультаций. Спокойная атмосфера, кондиционер, естественный свет.',
        photos: ['/img/offices/miniature_cab_2_pal.jpg'],
        services: ['natural_light', 'soundproof', 'couch', 'climate_control', 'wifi'],
        sortOrder: 2,
    },
    // Unbox Uni (Тбел Абусеридзе 38, Батуми)
    {
        id: 'unbox_uni_room_5',
        name: 'Кабинет 5',
        type: 'cabinet',
        hourlyRate: 20,
        capacity: 4,
        locationId: 'unbox_uni',
        area: 10,
        minBookingHours: 1,
        formats: ['individual'],
        description: 'Светлый кабинет для индивидуальной, детской и семейной терапии. Удобная мебель, приятная цветовая гамма.',
        photos: ['/img/offices/cabinet_5_ira.jpg'],
        services: ['natural_light', 'couch', 'climate_control', 'wifi'],
        sortOrder: 3,
    },
    {
        id: 'unbox_uni_room_6',
        name: 'Кабинет 6',
        type: 'cabinet',
        hourlyRate: 20,
        capacity: 4,
        locationId: 'unbox_uni',
        area: 16,
        minBookingHours: 1,
        formats: ['individual'],
        description: 'Просторный кабинет с песочной терапией. Подходит для индивидуальной работы, работы с детьми и семейных консультаций.',
        photos: ['/img/offices/cabinet_6_ira.jpg'],
        services: ['sandbox', 'natural_light', 'couch', 'climate_control', 'wifi'],
        sortOrder: 4,
    },
    {
        id: 'unbox_uni_room_7',
        name: 'Кабинет 7',
        type: 'cabinet',
        hourlyRate: 30,
        capacity: 20,
        locationId: 'unbox_uni',
        area: 25,
        minBookingHours: 1,
        formats: ['individual', 'group'],
        description: 'Большой групповой кабинет для тренингов, лекций, супервизий и мероприятий. Флипчарт, проектор, маркерная доска.',
        photos: ['/img/offices/cabinet_7_liza.webp'],
        services: ['flipchart', 'projector', 'whiteboard', 'climate_control', 'wifi', 'natural_light'],
        sortOrder: 5,
    },
    {
        id: 'unbox_uni_room_8',
        name: 'Кабинет 8',
        type: 'cabinet',
        hourlyRate: 30,
        capacity: 20,
        locationId: 'unbox_uni',
        area: 20,
        minBookingHours: 1,
        formats: ['individual', 'group'],
        description: 'Просторный групповой кабинет для групповой терапии, воркшопов и обучения. Современное оснащение.',
        photos: ['/img/offices/cabinet_8_liza.webp'],
        services: ['flipchart', 'whiteboard', 'climate_control', 'wifi'],
        sortOrder: 6,
    },
    {
        id: 'unbox_uni_room_9',
        name: 'Кабинет 9',
        type: 'cabinet',
        hourlyRate: 20,
        capacity: 10,
        locationId: 'unbox_uni',
        area: 16,
        minBookingHours: 1,
        formats: ['individual', 'group'],
        description: 'Уютный кабинет для индивидуальной и групповой работы. Отдельный вход, кондиционер.',
        services: ['private_entrance', 'couch', 'climate_control', 'wifi'],
        sortOrder: 7,
    },
    {
        id: 'unbox_uni_capsule_1',
        name: 'Капсула 1',
        type: 'capsule',
        hourlyRate: 10,
        capacity: 1,
        locationId: 'unbox_uni',
        area: 2,
        minBookingHours: 1,
        formats: ['individual'],
        description: 'Индивидуальная капсула для онлайн-сессий и сосредоточенной работы. Полная звукоизоляция, удобное кресло, монитор.',
        photos: ['/img/offices/miniature_capsule.jpeg'],
        services: ['soundproof', 'wifi', 'climate_control'],
        sortOrder: 8,
    },
    {
        id: 'unbox_uni_capsule_2',
        name: 'Капсула 2',
        type: 'capsule',
        hourlyRate: 10,
        capacity: 1,
        locationId: 'unbox_uni',
        area: 2,
        minBookingHours: 1,
        formats: ['individual'],
        description: 'Индивидуальная капсула для онлайн-сессий и сосредоточенной работы. Полная звукоизоляция, удобное кресло, монитор.',
        photos: ['/img/offices/miniature_capsule.jpeg'],
        services: ['soundproof', 'wifi', 'climate_control'],
        sortOrder: 9,
    },
];

// Cabinet/Room services with display metadata
export const CABINET_SERVICES: { id: string; label: string; emoji: string }[] = [
    { id: 'sandbox',         label: 'Песочница',           emoji: '🪣' },
    { id: 'natural_light',   label: 'Естественный свет',   emoji: '☀️' },
    { id: 'soundproof',      label: 'Звукоизоляция',       emoji: '🔇' },
    { id: 'couch',           label: 'Диван / Кушетка',     emoji: '🛋️' },
    { id: 'washbasin',       label: 'Умывальник',          emoji: '💧' },
    { id: 'private_entrance',label: 'Отдельный вход',      emoji: '🚪' },
    { id: 'coffee',          label: 'Кофемашина',          emoji: '☕' },
    { id: 'flipchart',       label: 'Флипчарт',            emoji: '📋' },
    { id: 'projector',       label: 'Проектор',            emoji: '📽️' },
    { id: 'whiteboard',      label: 'Маркерная доска',     emoji: '✏️' },
    { id: 'climate_control', label: 'Кондиционер',         emoji: '❄️' },
    { id: 'wifi',            label: 'Wi-Fi',               emoji: '📶' },
];

export const EXTRAS: ExtraOption[] = [
    { id: 'sandbox', name: 'Песочница', price: 15 },
    { id: 'sandbox_toys', name: 'Игрушки для песочной терапии', price: 10 },
    { id: 'flipchart', name: 'Флипчарт', price: 10 },
    { id: 'projector', name: 'Проектор', price: 20 },
];

export const SUBSCRIPTION_PLANS = [
    {
        id: 'WARM_START',
        name: 'Тёплый старт',
        hours: 10,
        price: 180,
        durationDays: 30,
        discountPercent: 10,
        formats: ['individual']
    },
    {
        id: 'REGULAR_PRACTITIONER',
        name: 'Регулярный практик',
        hours: 20,
        price: 340,
        durationDays: 30,
        discountPercent: 15,
        formats: ['individual'],
        perks: ['1 бесплатный перенос']
    },
    {
        id: 'PRO_PLUS',
        name: 'Профи+',
        hours: 40,
        bonusHours: 2,
        price: 640,
        durationDays: 45,
        discountPercent: 20,
        formats: ['individual', 'group'],
        perks: ['Приоритет', 'Внеурочный доступ', 'Рекомендация']
    },
    {
        id: 'GROUP_MASTER',
        name: 'Групповой мастер',
        hours: 16,
        price: 420,
        durationDays: 30,
        discountPercent: 25,
        formats: ['group'],
        perks: ['Анонс по базе']
    },
];
